import jenkins.*
import jenkins.model.*
import hudson.*
import hudson.model.*

import hudson.scm.*
import hudson.tasks.*
import com.cloudbees.hudson.plugins.folder.*

/*void processJob(Item job){
  if (job.name ==~ /.*None$/){
    println job.name
  }
}

void processFolder(Item folder){
    folder.getItems().each{
        println("Folder: ${folder.name}")
        if(it instanceof Folder){
            processFolder(it)
        }else{
            processJob(it)
        }
    }
}*/

node ()
{
    stage ('ENV Dump')
    {
        sh('env | sort -n')
        print("Params: ${params}")
    }

    stage('Cleanup')
    {
        def jen = Jenkins.instance
        def root = jen.getItemByFullName("${JOB_ROOT}", Folder)
        print("root: ${root}")

        def all_root_items = jen.getItems()
        print("All Top level Jobs: ${all_root_items}")
        all_root_items.each {
            print("iterator name: ${it.name}")
            if(it instanceof Folder){
                print("Folder: ${it.name}")
            }
        }
        /*jen.getItems().each{
            if(it instanceof Folder){
                processFolder(it)
            }else{
                processJob(it)
            }
        }*/
    }

}
