  /*properties(
    [
        parameters(
            [string(defaultValue: 'branch_name', name: 'gitlabSourceBranch'),
             string(defaultValue: 'repo', name: 'gitlabSourceRepo')]
            )

    ]
)*/

node()
{
    stage('ENV')
    {
        sh("env | sort -n")
        print("Params: ${params}")
    }
    gitlabCommitStatus(name: "test")
    {
        print("TEst Build Status Sent")
    }

}
