  properties(
    [
        parameters(
            [string(defaultValue: 'branch_name', name: 'gitlabSourceBranch'),
             string(defaultValue: 'repo', name: 'getlabSourceRepo')]
            )

    ]
)

node()
{
    stage('ENV')
    {
        sh("env | sort -n")
    }
}
